booru/philomena

- .github/workflows/elixir.yml
---
CI on push and pull_request for master branch instead only on any push.
> CI on push and pull_request

- priv/repo/seeds.json
---
- cleaned up pre-defined forum categories
- added forum categories tagging discussion and uploader discussion
> Clean up pre-defined forum categories

- Dockerfile.app
- Dockerfile.web
---
These changes are inteded to improve build performance of the dockerfiles by moving the copying of most assets into the late stages of the build and building dependencies using the minimal necessary fileset.
> Restructure docker files for improved performance

- README.md
- docker-compose.yml
- docker/gdpr/Dockerfile
- docker/gdpr/anonymize_ips.sh
- docker/gdpr/crontab.txt
- docker/gdpr/entry.sh
* I understand my contributions are for the benefit of Derpibooru and/or the Philomena software
- [ X] I understand all of the above
---
Fixes #18
> Add cron container and script to anonymize ips

- docker/gdpr/crontab.txt
- [X ] I understand all of the above
---
Changed the anonymize ips job to run every night at 3am
> Run anonymize ips cronjob at 3am

- .github/workflows/elixir.yml
- config/dev.exs
- config/test.exs
- docker-compose.yml
- docker/app/run-development
---
unify db names.
Fixes crong-job container using the wrong DB.
> unify db names

- assets/css/common/_base.scss
Make links in paragraphs bold.
> Bold in-text links.

- assets/css/common/_base.scss
---
- Increased logo size to 2em
> Increase logo size to 2em

- lib/philomena_web/templates/advert/_box.html.slime
Fix grammar, simplify by removing 'servers'
> Fix ad caption

- lib/philomena/users/ability.ex
Require a user id in comment/post abilities.
> Kill anon forum posting, I think?

- lib/philomena_web/user_auth.ex
---
fixed usage tracker which was accidentally removed by by one of the recent big merge commits. cherry picked from https://github.com/derpibooru/philomena/commit/78dac4df706b8a3d4430c91575fefc255fa57855
Author of that commit is liamwhite
> re-add usage tracker

- assets/css/common/_base.scss
Just noticed this in a forum post, and this class seems to cover all of the above.
> Bold links in forum/convo/comment message body.

- lib/philomena/users/user.ex
---
Without this addition, users are not able to actually set any of these themes in their settings. This is in response to the addition of themes in issue #7.
> Added new themes to the changeset

- lib/philomena/scrapers/twitter.ex
Cherry-picked https://github.com/philomena-dev/philomena/commit/cf72729ae7d38620cb8b9ea85be009a9ee0ba63e
Co-Authored-By: liamwhite <liamwhite@users.noreply.github.com>
---
Fix twitter scraper again, by cherry-picking a commit from philomena-dev.
Co-authored by liamwhite.
> fix twitter scraper

- lib/philomena/users/user.ex
---
fix avatar upload size checks
> fix avatar upload size checks

- lib/philomena/tags.ex
- lib/philomena/tags/tag.ex
Add limits on tag name lengths, both frontend and backend.
> Limit length of tag names

- lib/philomena_web/controllers/conversation_controller.ex
- lib/philomena_web/controllers/image/comment_controller.ex
- lib/philomena_web/controllers/image/source_controller.ex
- lib/philomena_web/controllers/image/tag_controller.ex
- lib/philomena_web/controllers/image_controller.ex
- lib/philomena_web/controllers/topic/post_controller.ex
- lib/philomena_web/controllers/topic_controller.ex
- lib/philomena_web/plugs/limit_plug.ex
---
Cherry-picked three commits regarding web-ui rate-limiting of non-staff users.
Co-authored by liamwhite
> Rate limiting non-staff users.

- assets/static/robots.txt
Co-Authored-By: liamwhite <liamwhite@users.noreply.github.com>
---
disallow bad/spammy bots that are not used by users targeted by philomena.
Also, cherry picked https://github.com/philomena-dev/philomena/commit/7046857cbda737d29576ae1967cb1d2cd43b1f4c
> disallow bad/spammy bots, also search engine spiders should do their own searching

- lib/philomena_web/controllers/image/destroy_controller.ex
- lib/philomena_web/plugs/limit_plug.ex
---
Adds the ability to force staff to conform to limits imposed by `PhilomenaWeb.LimitPlug`, and add a `10 every 10 minutes` limit on destroying images.
> Somewhat damaged patch 1

- lib/philomena_web/templates/layout/_header.html.slime
---
- Change search field placeholder to show a comma separated example
> Change search field placeholder to show a comma separated example

- docker/gdpr/scripts/anonymize_comments.sh
- docker/gdpr/scripts/anonymize_tag_changes.sh
* I understand my contributions are for the benefit of Derpibooru and/or the Philomena software
---
> Some small fixes to the gdpr-con docker container

- docker/gdpr/Dockerfile
- docker/gdpr/crontab.txt
- docker/gdpr/entry.sh
- docker/gdpr/scripts/anonymize_comments.sh
- docker/gdpr/scripts/anonymize_images.sh
- docker/gdpr/scripts/anonymize_posts.sh
- docker/gdpr/scripts/anonymize_reports.sh
- docker/gdpr/scripts/anonymize_source_changes.sh
- docker/gdpr/scripts/anonymize_tag_changes.sh
- docker/gdpr/scripts/anonymize_user_ips.sh
---
Add the user_ips table to be pruned after 14 days, additionally allows checkins to a healthchecker to verify the cleaner is working.
> add healthcheck option to gdpr container, add user_ips to cleaned tables

- lib/philomena/users/user.ex
- lib/philomena_web/templates/setting/edit.html.slime
---
Backport of the change "set lower limit on user pagination to 1", from upstream philomena.
> Backport: set lower limit on user pagination to 1
