lib/philomena_web/templates/image/new.html.slime
---
Disabled anonymous content upload in the UI without being authenticated.
The API already is covered by https://github.com/booru/philomena/blob/master/lib/philomena_web/plugs/api_require_authorization_plug.ex
Fixes #17
=> require login for content upload in UI

lib/philomena_web/templates/image/_tags.html.slime
---
- require user to be logged in for tag editing in UI. Contains a captcha, so no need to edit backend components.
=> Disable tag editing without login in UI

lib/philomena_web/templates/image/_source.html.slime
---
- disabled source editing without login in UI. Has captcha, thus no need to change backend.
=> disable source editing without login in UI

README.md
---
Just a bit of documentation for the image_url_root config variable that can be used to change the base url for images
=> Add documentation for image_url_root config variable

lib/philomena/users/ability.ex, lib/philomena_web/controllers/conversation_controller.ex, lib/philomena_web/templates/conversation/index.html.slime, lib/philomena_web/templates/profile/show.html.slime, lib/philomena_web/views/conversation_view.ex, lib/philomena_web/views/profile_view.ex
Adds a (currently) mod-only permission to create new Conversations (private messages), and implements authorization-blocks in ConversationController, and link/button-hiding in profile and conversations pages.
Closes #44
=> Disable creating new Conversations (private-message threads) for normal users.

docker-compose.yml
Removes duplicate SMTP_ environment variable entries, which docker-compose does not like at all.
=> Remove duplicate SMTP_ env var entries

lib/philomena_web/controllers/registration_controller.ex
Guess these got lost in the multiple big-PR attempts.
=> Re-add name length and notable plugs to registration controller.

.env.example, docker-compose.yml, lib/philomena/application.ex, lib/philomena_web/plugs/dev_only_plug.ex, lib/philomena_web/router.ex
- Fixes app name in email-related config environment variable loading
- Adds `:mailer_address` env var loading from `MAILER_ADDRESS`, with a generic default
- Adds a simple `DevOnlyPlug` that checks `:app_env`, and redirects to / unless it's "dev"
- Uses this plug to enable (for `APP_ENV=dev` only) the `Bamboo.SentEmailViewerPlug`, which shows emails sent via the `LocalAdapter` at /sent_emails.
=> Multiple email-related fixes.

lib/philomena/users/user_notifier.ex
Having these headers avoids some spam filters.
=> Add Message-ID and Date headers to outgoing emails.

assets/css/common/_base.scss, lib/philomena_web/controllers/registration/totp_controller.ex, lib/philomena_web/plugs/notable_name_plug.ex, lib/philomena_web/templates/registration/new.html.slime, lib/philomena_web/user_auth.ex
Improve and generify restricted name message, bold the link in it (and links in all flash messages), and set 80-char limit in the form field.
=> Registration tweaks.

lib/philomena_web/templates/image/_image_page.html.slime
---
adjusted image uploaded wait message as requested, so that people know that images will be visible only a couple of minutes after uploading them.
=> adjust image uploaded wait message as requested

lib/philomena_web/templates/admin/user/index.html.slime, lib/philomena_web/views/admin/user_view.ex
Hide emails from non-admins, except for mods with a special permission.
Relies on permission accidentally prematurely added to ability.ex in PR #55.
=> Hide Emails

lib/philomena/users/ability.ex, lib/philomena_web/controllers/conversation/report_controller.ex, lib/philomena_web/controllers/duplicate_report_controller.ex, lib/philomena_web/controllers/gallery/report_controller.ex, lib/philomena_web/controllers/image/comment/report_controller.ex, lib/philomena_web/controllers/image/report_controller.ex, lib/philomena_web/controllers/profile/commission/report_controller.ex, lib/philomena_web/controllers/profile/report_controller.ex, lib/philomena_web/controllers/topic/post/report_controller.ex, lib/philomena_web/plugs/authorized_reporter_plug.ex, lib/philomena_web/templates/comment/_comment_options.html.slime, lib/philomena_web/templates/gallery/show.html.slime, lib/philomena_web/templates/image/_options.html.slime, lib/philomena_web/templates/post/_post_options.html.slime, lib/philomena_web/templates/profile/commission/_listing_sidebar.html.slime, lib/philomena_web/templates/profile/show.html.slime, lib/philomena_web/views/comment_view.ex, lib/philomena_web/views/conversation_view.ex, lib/philomena_web/views/gallery_view.ex, lib/philomena_web/views/image/comment_view.ex, lib/philomena_web/views/image_view.ex, lib/philomena_web/views/post_view.ex, lib/philomena_web/views/profile/commission_view.ex, lib/philomena_web/views/profile_view.ex, lib/philomena_web/views/topic/post_view.ex
Adds new permission requiring log-in to report, added controller checks and button toggles for all (I hope) possible report origins.
=> Disable anon reports, site-wide.

lib/philomena/users/user.ex
---
This change was made in order to make the error messages when uploading avatars that are out of spec clearer. This was done in order to solve issue #56.
=> Clear avatar change errors

lib/philomena_web/controllers/confirmation_controller.ex
---
When a user successfully confirms their email this change will redirect them automatically to the login page where they may log in with their newly confirmed account.
This request was made in issue #58 and that issue should be closed if these changes are merged.
Closes #58
=> Change confirmation redirect

assets/js/upload.js, lib/philomena/scrapers/tumblr.ex, lib/philomena_web/controllers/api/json/oembed_controller.ex, lib/philomena_web/controllers/registration/totp_controller.ex, lib/philomena_web/templates/admin/user/index.html.slime, lib/philomena_web/templates/profile/_admin_block.html.slime, lib/philomena_web/templates/registration/edit.html.slime, lib/philomena_web/templates/registration/totp/edit.html.slime
---
- add missing 2fa icon to admin thing and consistent spelling of "two factor"
- display unconfirmed users in admin users list
- fix discord oembed cards
- fix tumblr scrapes for text posts 
- require confirmation for navigation away from image upload form
=> Cherry-picked some fixes from philomena-dev (2020-08)

lib/philomena/images/id_validator.ex, lib/philomena/images/image.ex, lib/philomena/users/ability.ex, lib/philomena_web/controllers/api/json/image_controller.ex, lib/philomena_web/plugs/id_validation_plug.ex
- Add Ecto cast of ID to repo creation changeset if an ID was provided.
- Create `Philomena.Images.IDValidator` which provides `validate_id/2` to check if ID matches the provided `source_url`, along with structure containing map of ID number ranges to sites/source url bases (currently only Derpibooru).
- Create `PhilomenaWeb.IDValidationPlug` to handle checking for valid IDs (string or numeric IDs should work), and passing or rejecting uploads.
- Insert new plug into the API image controller.
=> Add to API the ability to specify image ID (must agree with source_url)

docker-compose.yml
---
Elastic mounted the wrong folder into the FS: https://www.elastic.co/guide/en/elasticsearch/reference/7.8/docker.html
Before elastic is started again, ensure that the permissions for the ./local-data/elastic folder are 777 so elastic can spawn the proper folders inside.
=> fix elastic data mount path

assets/css/common/_base.scss
Default URL wrapping (at least as philomena has things set up) is:
* Safari: no wrapping except on hyphens/dashes in the URL, overflow off into oblivion screwing with page width (esp. on mobile devices).
* Firefox: wrap at slashes (and possibly other special characters?)
* Chrome: wrap anywhere
This change makes Safari behave like Chrome, without affecting Firefox.
Issue was reported regarding source URLs on image pages, but made it general to all a elements in case this could be messing with mobile layout elsewhere (and I don't think it will break anything).
=> Make Safari wrap URL links

config/quick_tag_table.json
---
Adds the G5 Movie Tags to the quicktag box
=> Add G5 quicktags
